export const FETCHING_COCKTAILS_REQUEST = 'FETCHING_COCKTAILS_REQUEST';
export const FETCHING_COCKTAILS_SUCCESS = 'FETCHING_COCKTAILS_SUCCESS';
export const FETCHING_COCKTAILS_FAILURE = 'FETCHING_COCKTAILS_FAILURE';
