export const drink = {
  details: [
    {
      dateModified: '2016-08-31 19:48:22',
      idDrink: '16108',
      strAlcoholic: 'Alcoholic',
      strCategory: 'Cocktail',
      strCreativeCommonsConfirmed: 'No',
      strDrink: '9 1/2 Weeks',
      strDrinkAlternate: null,
      strDrinkDE: null,
      strDrinkES: null,
      strDrinkFR: null,
      strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/xvwusr1472669302.jpg',
      'strDrinkZH-HANS': null,
      'strDrinkZH-HANT': null,
      strGlass: 'Cocktail glass',
      strIBA: null,
      strIngredient1: 'Absolut Citron',
      strIngredient2: 'Orange Curacao',
      strIngredient3: 'Strawberry liqueur',
      strIngredient4: 'Orange juice',
      strIngredient5: null,
      strIngredient6: null,
      strIngredient7: null,
      strIngredient8: null,
      strIngredient9: null,
      strIngredient10: null,
      strIngredient11: null,
      strIngredient12: null,
      strIngredient13: null,
      strIngredient14: null,
      strIngredient15: null,
      strInstructions:
        'Combine all ingredients in glass mixer. Chill and strain into Cocktail glass. Garnish with sliced strawberry.',
      strInstructionsDE:
        'Alle Zutaten in einem Glasmischer vermengen. Abkühlen lassen und in das Cocktailglas abseihen. Mit Erdbeerscheiben garnieren.',
      strInstructionsES: null,
      strInstructionsFR: null,
      'strInstructionsZH-HANS': null,
      'strInstructionsZH-HANT': null,
      strMeasure1: '2 oz ',
      strMeasure2: '1/2 oz ',
      strMeasure3: '1 splash ',
      strMeasure4: '1 oz ',
      strMeasure5: null,
      strMeasure6: null,
      strMeasure7: null,
      strMeasure8: null,
      strMeasure9: null,
      strMeasure10: null,
      strMeasure11: null,
      strMeasure12: null,
      strMeasure13: null,
      strMeasure14: null,
      strMeasure15: null,
      strTags: null,
      strVideo: null,
    },
  ],
  idDrink: '16108',
  strDrink: '9 1/2 Weeks',
  strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/xvwusr1472669302.jpg',
};

export const filteredIngredients = [
  'Absolut Citron',
  'Orange Curacao',
  'Strawberry liqueur',
  'Orange juice',
];

export const filteredMeasures = ['2 oz ', '1/2 oz ', '1 splash ', '1 oz '];

export const measuresAndIngredients = [
  '2 oz - Absolut Citron',
  '1/2 oz - Orange Curacao',
  '1 splash - Strawberry liqueur',
  '1 oz - Orange juice',
];
